<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$selectElem = Array(
	"ID",
	"IBLOCK_ID",
	"NAME",
	"PROPERTY_LANDING_LINK",
);
$filterElem = Array("IBLOCK_ID"=>6, "CODE" => 'krem_akrustal_klassicheskiy_165_ml_test');
$res = CIBlockElement::GetList(Array(), $filterElem, false, Array("nPageSize"=>1), $selectElem);
while($ob = $res->GetNextElement()){
	$arPropLanding = $ob->GetFields();
}
/*\Akrustal\lib\Utils::pr($arPropLanding);*/

$arParams = array(
	#"COMMON_SHOW_CLOSE_POPUP" => 'Y', # Орлов А. показывать кнопку "Продолжить покупки" в окне добавления довара
	"COMPONENT_TEMPLATE" => "master",
	"IBLOCK_TYPE" => "catalog",
	"IBLOCK_ID" => "6",
	"ADD_PICT_PROP" => "MORE_PHOTO",
	"LABEL_PROP" => array(
		0 => "NEWPRODUCT",
		1 => "SPECIALOFFER",
		2 => "SALELEADER",
	),
	"LABEL_PROP_MOBILE" => array(
	),
	"LIST_LABEL_PROP_POSITION" => "bottom-left",
	"DETAIL_LABEL_PROP_POSITION" => "top-left",
	"MESS_BTN_BUY" => "Купить",
	"MESS_BTN_ADD_TO_BASKET" => "Купить",
	"MESS_BTN_COMPARE" => "Сравнение",
	"MESS_BTN_DETAIL" => "Подробнее",
	"MESS_NOT_AVAILABLE" => "Нет в наличии",
	"MESS_BTN_SUBSCRIBE" => "Подписаться",
	"ARTNUMBER_PROP" => "ARTNUMBER",
	"PRICE_PROP" => "PRICE",
	"DISCOUNT_PROP" => "DISCOUNT",
	"CURRENCY_PROP" => "CURRENCY",
	"PRICE_DECIMALS" => "0",
	"SHOW_OLD_PRICE" => "Y",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/catalog/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"AJAX_OPTION_ADDITIONAL" => "",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "Y",
	"CACHE_GROUPS" => "Y",
	"USE_MAIN_ELEMENT_SECTION" => "Y",
	"DETAIL_STRICT_SECTION_CHECK" => "Y",
	"SET_LAST_MODIFIED" => "Y",
	"SET_TITLE" => "Y",
	"ADD_SECTIONS_CHAIN" => "Y",
	"ADD_ELEMENT_CHAIN" => "Y",
	"ADD_CONTAINER" => "N",
	"IS_USE_CART" => "Y",
	"USE_FAVORITE" => "Y",
	"FAVORITE_COUNT_PROP" => "FAVORITE_COUNT",
	"USE_FILTER" => "Y",
	"FILTER_HIDE_ON_MOBILE" => "N",
	"INSTANT_RELOAD" => "Y",
	"ACTION_VARIABLE" => "action",
	"PRODUCT_ID_VARIABLE" => "id",
	"USE_COMPARE" => "N",
	"PRICE_CODE" => array(
	),
	"USE_PRICE_COUNT" => "N",
	"SHOW_PRICE_COUNT" => "1",
	"PRICE_VAT_INCLUDE" => "Y",
	"PRICE_VAT_SHOW_VALUE" => "N",
	"BASKET_URL" => "/cart/",
	"USE_PRODUCT_QUANTITY" => "Y",
	"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"ADD_PROPERTIES_TO_BASKET" => "Y",
	"PRODUCT_PROPS_VARIABLE" => "prop",
	"PARTIAL_PRODUCT_PROPERTIES" => "Y",
	"PRODUCT_PROPERTIES" => array(
	),
	"SECTION_ADD_TO_BASKET_ACTION" => "BUY",
	"DETAIL_ADD_TO_BASKET_ACTION" => array(
		0 => "ADD",
		1 => "ASK",
	),
	"SEARCH_PAGE_RESULT_COUNT" => "50",
	"SEARCH_RESTART" => "N",
	"SEARCH_NO_WORD_LOGIC" => "Y",
	"SEARCH_USE_LANGUAGE_GUESS" => "Y",
	"SEARCH_CHECK_DATES" => "Y",
	"SHOW_TOP_ELEMENTS" => "Y",
	"TOP_ELEMENT_COUNT" => "9",
	"TOP_LINE_ELEMENT_COUNT" => "3",
	"TOP_ELEMENT_SORT_FIELD" => "sort",
	"TOP_ELEMENT_SORT_ORDER" => "asc",
	"TOP_ELEMENT_SORT_FIELD2" => "id",
	"TOP_ELEMENT_SORT_ORDER2" => "desc",
	"TOP_PROPERTY_CODE" => array(
		0 => "",
		1 => "",
	),
	"SECTION_COUNT_ELEMENTS" => "N",
	"SECTION_TOP_DEPTH" => "2",
	"SECTIONS_SHOW_PARENT_NAME" => "Y",
	"CATALOG_VIEW_MODE" => "VIEW_ELEMENTS",
	"SECTIONS_VIEW_MODE" => "LINE",
	"PAGE_ELEMENT_COUNT" => "12",
	"LINE_ELEMENT_COUNT" => "3",
	"ELEMENT_SORT_FIELD" => "sort",
	"ELEMENT_SORT_ORDER" => "asc",
	"ELEMENT_SORT_FIELD2" => "id",
	"ELEMENT_SORT_ORDER2" => "desc",
	"LIST_PROPERTY_CODE" => array(
		0 => "BRAND_REF",
		1 => "WEIGHT",
		2 => "NETTO",
		3 => "srok_hraneniya",
		4 => "usloviya_hraneniya",
		5 => "FORM",
		6 => "",
	),
	"LIST_PROPERTY_CODE_MOBILE" => array(
	),
	"INCLUDE_SUBSECTIONS" => "Y",
	"LIST_META_KEYWORDS" => "-",
	"LIST_META_DESCRIPTION" => "-",
	"LIST_BROWSER_TITLE" => "-",
	"SECTION_BACKGROUND_IMAGE" => "UF_BACKGROUND_IMAGE",
	"SHOW_SECTION_DESCRIPTION" => "top",
	"LIST_PRODUCT_BLOCKS_ORDER" => "preview,price,quantity,buttons",
	"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
	"LIST_ENLARGE_PRODUCT" => "STRICT",
	"DETAIL_PROPERTY_CODE" => array(
		0 => "ARTNUMBER",
		1 => "BRAND_REF",
		2 => "WEIGHT",
		3 => "NETTO",
		4 => "HTML_VIDEO",
		5 => "VOLUME",
		6 => "srok_hraneniya",
		7 => "usloviya_hraneniya",
		8 => "FORM",
		9 => "",
	),
	"DETAIL_META_KEYWORDS" => "-",
	"DETAIL_META_DESCRIPTION" => "-",
	"DETAIL_BROWSER_TITLE" => "-",
	"DETAIL_SET_CANONICAL_URL" => "Y",
	"SECTION_ID_VARIABLE" => "SECTION_ID",
	"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
	"DETAIL_BACKGROUND_IMAGE" => "-",
	"SHOW_DEACTIVATED" => "N",
	"DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(
		0 => "ARTNUMBER",
		1 => "BRAND_REF",
		2 => "WEIGHT",
		3 => "VOLUME",
		4 => "FORM",
	),
	"DETAIL_USE_VOTE_RATING" => "N",
	"DETAIL_USE_COMMENTS" => "Y",
	"DETAIL_BRAND_USE" => "Y",
	"DETAIL_DISPLAY_NAME" => "Y",
	"DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "price,buttons", #"preview,props,price,buttons", Орлов А.
	"DETAIL_SHOW_POPULAR" => "Y",
	"DETAIL_SHOW_VIEWED" => "Y",
	"LINK_IBLOCK_TYPE" => "catalog",
	"LINK_IBLOCK_ID" => "6",
	"LINK_PROPERTY_SID" => "RECOMMEND",
	"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
	"USE_STORE" => "N",
	"PAGER_TEMPLATE" => "master",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "Y",
	"PAGER_TITLE" => "Товары",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	"PAGER_SHOW_ALL" => "Y",
	"PAGER_BASE_LINK_ENABLE" => "N",
	"LAZY_LOAD" => "Y",
	"LOAD_ON_SCROLL" => "N",
	"TEMPLATE_AJAXID" => "catalog",
	"SET_STATUS_404" => "Y",
	"SHOW_404" => "Y",
	"FILE_404" => "",
	"COMPATIBLE_MODE" => "Y",
	"USE_ELEMENT_COUNTER" => "Y",
	"DISABLE_INIT_JS_IN_COMPONENT" => "Y",
	"USE_ENHANCED_ECOMMERCE" => "Y",
	"DATA_LAYER_NAME" => "dataLayer",
	"BRAND_PROPERTY" => "BRAND_REF",
	"USE_REVIEW" => "Y",
	"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "S",
	"USE_SHARE" => "N",
	"SOCIAL_COUNTER" => "N",
	"SOCIAL_COPY" => "first",
	"SOCIAL_LIMIT" => "",
	"SOCIAL_SIZE" => "m",
	"DETAIL_SOCIAL_SERVICES" => array(
		0 => "facebook",
		1 => "odnoklassniki",
		2 => "telegram",
		3 => "twitter",
		4 => "vkontakte",
		5 => "",
	),
	"MESS_BTN_LAZY_LOAD" => "Показать ещё",
	"DETAIL_ADD_TO_BASKET_ACTION_PRIMARY" => array(
		0 => "ADD",
	),
	"MESS_BTN_ASK" => "Заказать в 1 клик",
	"LINK_BTN_ASK" => "/include/forms/product_ask/?element_id=#ELEMENT_ID#",
	"DETAIL_TAB_PROPERTIES" => array(
		0 => "DOC_FILE",
		1 => "HTML_VIDEO",
		2 => "PRICE_TABLE",
	),
	"DETAIL_TABS" => array(
		0 => "detail",
		1 => "props",
		/*2 => "comments",*/
		3 => "prop_HTML_VIDEO",
		4 => "prop_DOC_FILE",
		5 => "reviews",
	),
	"DETAIL_TABS_ORDER" => "detail,props,prop_HTML_VIDEO,prop_DOC_FILE,reviews",
	"MESS_DESCRIPTION_TAB" => "Описание",
	"MESS_PROPERTIES_TAB" => "Характеристики",
	"DETAIL_BLOG_USE" => "Y",
	"DETAIL_VK_USE" => "Y",
	"DETAIL_VK_API_ID" => "6285651",
	"DETAIL_FB_USE" => "Y",
	"MESS_COMMENTS_TAB" => "Комментарии",
	"DETAIL_BLOCK_LINES" => array(
		/*0 => "prop_DOC_FILE",
		1 => "prop_PRICE_TABLE",*/
	),
	#"DETAIL_BLOCK_LINES_ORDER" => "prop_PRICE_TABLE,prop_DOC_FILE,comments",
	"DETAIL_BLOCK_LINES_ORDER" => "prop_DOC_FILE,comments",
	"DETAIL_BLOCK_LINES_PROPERTIES" => array(
		0 => "DOC_FILE",
		/*1 => "PRICE_TABLE",*/
	),
	"DETAIL_BLOG_URL" => "catalog_comments",
	"DETAIL_BLOG_EMAIL_NOTIFY" => "Y",
	"DETAIL_FB_APP_ID" => "",
	"IBLOCK_ID_LANDING" => "35",
	"PROPERTY_LANDING" => array(
		0 => "BACKGROUND_IMAGE",
		1 => "PROP_BANNER_1",
		2 => "PROP_BANNER_2",
		3 => "PROP_BANNER_3",
		4 => "PROP_DESCR_1",
		5 => "PROP_PLUS_1",
		6 => "PROP_PLUS_2",
		7 => "PROP_PLUS_3",
		8 => "PROP_PLUS_4",
		9 => "PROP_REVIEW_1",
		10 => "PROP_DOC_1",
		11 => "PROP_QUEST_2",
		12 => "PROP_QUEST_3",
		13 => "PROP_SOC_SERV",
		14 => "PROP_ITEMS_1",
		15 => "PROP_GALLERY_1",
	),
	"PROPERTY_LANDING_LINK" => "LANDING_LINK",
	"SECTIONS_SHOW_SIDEBAR" => "N",
	"LIST_SHOW_SIDEBAR" => "Y",
	"DETAIL_SHOW_SIDEBAR" => "Y",
	"SORTER_ACTION_PARAM_NAME" => "alfaction",
	"SORTER_ACTION_PARAM_VALUE" => "alfavalue",
	"SORTER_CHOSE_TEMPLATES_SHOW" => "Y",
	"SORTER_CNT_TEMPLATES" => "2",
	"SORTER_CNT_TEMPLATES_0" => "Плитка",
	"SORTER_CNT_TEMPLATES_NAME_0" => "vid-2",
	"SORTER_CNT_TEMPLATES_1" => "Список",
	"SORTER_CNT_TEMPLATES_NAME_1" => "vid-1",
	"SORTER_DEFAULT_TEMPLATE" => "vid-1",
	"SORTER_SORT_BY_SHOW" => "Y",
	"SORTER_SORT_BY_NAME" => array(
		0 => "sort",
		1 => "name",
		2 => "PROPERTY_PRICE",
		3 => "",
	),
	"SORTER_SORT_BY_DEFAULT" => "sort_asc",
	"SORTER_OUTPUT_OF_SHOW" => "Y",
	"SORTER_OUTPUT_OF" => array(
		0 => "",
		1 => "12",
		2 => "24",
		3 => "36",
		4 => "48",
		5 => "",
	),
	"SORTER_OUTPUT_OF_DEFAULT" => "12",
	"LIST_TEMPLATE" => "master",
	"DETAIL_TEMPLATE" => "master",
	"USE_SORTER" => "Y",
	"SORTER_TEMPLATE" => "master",
	"FILTER_NAME" => "",
	"FILTER_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_PROPERTY_CODE" => array(
		0 => "PRICE"
	),
	"FILTER_PRICE_CODE" => array(
		0 => "BASE",
	),
	"FILTER_SCROLL_PROPS" => array(
		0 => "BRAND_REF",
	),
	"FILTER_SEARCH_PROPS" => array(
		0 => "BRAND_REF",
	),
	"FEATURE_FILTER_USER_FIELDS" => "UF_FEATURED_FILTER",
	"FILTER_THEME" => "default",
	"HIDE_SECTION_NAME" => "N",
	"SECTIONS_COL_XS" => "6",
	"SECTIONS_COL_SM" => "3",
	"SECTIONS_COL_MD" => "3",
	"SECTIONS_COL_LG" => "3",
	"HIDE_NOT_AVAILABLE" => "N",
	"HIDE_NOT_AVAILABLE_OFFERS" => "N",
	"USER_CONSENT" => "N",
	"USER_CONSENT_ID" => "0",
	"USER_CONSENT_IS_CHECKED" => "Y",
	"USER_CONSENT_IS_LOADED" => "N",
	"MESSAGES_PER_PAGE" => "10",
	"USE_CAPTCHA" => "Y",
	"REVIEW_AJAX_POST" => "Y",
	"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
	"FORUM_ID" => "1",
	"URL_TEMPLATES_READ" => "",
	"SHOW_LINK_TO_FORUM" => "Y",
	"CONVERT_CURRENCY" => "N",
	"USE_GIFTS_DETAIL" => "Y",
	"USE_GIFTS_SECTION" => "Y",
	"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
	"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
	"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
	"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
	"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
	"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "4",
	"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
	"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
	"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
	"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
	"GIFTS_SHOW_OLD_PRICE" => "Y",
	"GIFTS_SHOW_NAME" => "Y",
	"GIFTS_SHOW_IMAGE" => "Y",
	"GIFTS_MESS_BTN_BUY" => "Выбрать",
	"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
	"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
	"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
	"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
	"SEF_URL_TEMPLATES" => array(
		"sections" => "",
		"section" => "#SECTION_CODE_PATH#/",
		"element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		"compare" => "compare/?action=#ACTION_CODE#",
		"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
	),
	"VARIABLE_ALIASES" => array(
		"compare" => array(
			"ACTION_CODE" => "action",
		),
	)
);

$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	"landings",
	Array(
		"IBLOCK_TYPE" => "",
		"IBLOCK_ID" => 35,
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "sac",
		"ELEMENT_SORT_FIELD2" => isset($alfaCSortType) ? $arParams["ELEMENT_SORT_FIELD"] : $arParams["ELEMENT_SORT_FIELD2"],
		"ELEMENT_SORT_ORDER2" => isset($alfaCSortType) ? $arParams["ELEMENT_SORT_ORDER"] : $arParams["ELEMENT_SORT_ORDER2"],
		"PROPERTY_CODE" => $arParams["PROPERTY_LANDING"],
		"PROPERTY_CODE_MOBILE" => $arParams["LIST_PROPERTY_CODE_MOBILE"],
		"META_KEYWORDS" => $arParams["LIST_META_KEYWORDS"],
		"META_DESCRIPTION" => $arParams["LIST_META_DESCRIPTION"],
		"BROWSER_TITLE" => $arParams["LIST_BROWSER_TITLE"],
		"SET_LAST_MODIFIED" => $arParams["SET_LAST_MODIFIED"],
		"INCLUDE_SUBSECTIONS" => $arParams["INCLUDE_SUBSECTIONS"],
		"BASKET_URL" => $arParams["BASKET_URL"],
		"ACTION_VARIABLE" => $arParams["ACTION_VARIABLE"],
		"PRODUCT_ID_VARIABLE" => $arParams["PRODUCT_ID_VARIABLE"],
		"SECTION_ID_VARIABLE" => $arParams["SECTION_ID_VARIABLE"],
		"PRODUCT_QUANTITY_VARIABLE" => $arParams["PRODUCT_QUANTITY_VARIABLE"],
		"PRODUCT_PROPS_VARIABLE" => $arParams["PRODUCT_PROPS_VARIABLE"],
		"FILTER_NAME" => $arParams["FILTER_NAME"],
		"CACHE_TYPE" => $arParams["CACHE_TYPE"],
		"CACHE_TIME" => $arParams["CACHE_TIME"],
		"CACHE_FILTER" => $arParams["CACHE_FILTER"],
		"CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
		"SET_TITLE" => $arParams["SET_TITLE"],
		"MESSAGE_404" => $arParams["~MESSAGE_404"],
		"SET_STATUS_404" => $arParams["SET_STATUS_404"],
		"SHOW_404" => $arParams["SHOW_404"],
		"FILE_404" => $arParams["FILE_404"],
		"DISPLAY_COMPARE" => $arParams["USE_COMPARE"],
		"PAGE_ELEMENT_COUNT" => 100,
		"LINE_ELEMENT_COUNT" => $arParams["LINE_ELEMENT_COUNT"],
		"PRICE_CODE" => $arParams["PRICE_CODE"],
		"USE_PRICE_COUNT" => $arParams["USE_PRICE_COUNT"],
		"SHOW_PRICE_COUNT" => $arParams["SHOW_PRICE_COUNT"],

		"PRICE_VAT_INCLUDE" => $arParams["PRICE_VAT_INCLUDE"],
		"USE_PRODUCT_QUANTITY" => $arParams['USE_PRODUCT_QUANTITY'],
		"ADD_PROPERTIES_TO_BASKET" => (isset($arParams["ADD_PROPERTIES_TO_BASKET"]) ? $arParams["ADD_PROPERTIES_TO_BASKET"] : ''),
		"PARTIAL_PRODUCT_PROPERTIES" => (isset($arParams["PARTIAL_PRODUCT_PROPERTIES"]) ? $arParams["PARTIAL_PRODUCT_PROPERTIES"] : ''),
		"PRODUCT_PROPERTIES" => $arParams["PRODUCT_PROPERTIES"],

		"DISPLAY_TOP_PAGER" => $arParams["DISPLAY_TOP_PAGER"],
		"DISPLAY_BOTTOM_PAGER" => $arParams["DISPLAY_BOTTOM_PAGER"],
		"PAGER_TITLE" => $arParams["PAGER_TITLE"],
		"PAGER_SHOW_ALWAYS" => $arParams["PAGER_SHOW_ALWAYS"],
		"PAGER_TEMPLATE" => $arParams["PAGER_TEMPLATE"],
		"PAGER_DESC_NUMBERING" => $arParams["PAGER_DESC_NUMBERING"],
		"PAGER_DESC_NUMBERING_CACHE_TIME" => $arParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
		"PAGER_SHOW_ALL" => $arParams["PAGER_SHOW_ALL"],
		"PAGER_BASE_LINK_ENABLE" => $arParams["PAGER_BASE_LINK_ENABLE"],
		"PAGER_BASE_LINK" => $arParams["PAGER_BASE_LINK"],
		"PAGER_PARAMS_NAME" => $arParams["PAGER_PARAMS_NAME"],
		"LAZY_LOAD" => $arParams["LAZY_LOAD"],
		"MESS_BTN_LAZY_LOAD" => $arParams["~MESS_BTN_LAZY_LOAD"],
		"LOAD_ON_SCROLL" => $arParams["LOAD_ON_SCROLL"],
		"SOCIAL_SERVICES" => $arParams["DETAIL_SOCIAL_SERVICES"],

		"OFFERS_CART_PROPERTIES" => $arParams["OFFERS_CART_PROPERTIES"],
		"OFFERS_FIELD_CODE" => $arParams["LIST_OFFERS_FIELD_CODE"],
		"OFFERS_PROPERTY_CODE" => $arParams["LIST_OFFERS_PROPERTY_CODE"],
		"OFFERS_SORT_FIELD" => $arParams["OFFERS_SORT_FIELD"],
		"OFFERS_SORT_ORDER" => $arParams["OFFERS_SORT_ORDER"],
		"OFFERS_SORT_FIELD2" => $arParams["OFFERS_SORT_FIELD2"],
		"OFFERS_SORT_ORDER2" => $arParams["OFFERS_SORT_ORDER2"],
		"OFFERS_LIMIT" => $arParams["LIST_OFFERS_LIMIT"],

		"SECTION_ID" => $arPropLanding["PROPERTY_".$arParams["PROPERTY_LANDING_LINK"]."_VALUE"],
		"SECTION_CODE" => "",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"USE_MAIN_ELEMENT_SECTION" => $arParams["USE_MAIN_ELEMENT_SECTION"],
		'CONVERT_CURRENCY' => $arParams['CONVERT_CURRENCY'],
		'CURRENCY_ID' => $arParams['CURRENCY_ID'],
		'HIDE_NOT_AVAILABLE' => $arParams["HIDE_NOT_AVAILABLE"],
		'HIDE_NOT_AVAILABLE_OFFERS' => $arParams["HIDE_NOT_AVAILABLE_OFFERS"],

		'LABEL_PROP' => $arParams['LABEL_PROP'],
		'LABEL_PROP_MOBILE' => $arParams['LABEL_PROP_MOBILE'],
		'LABEL_PROP_POSITION' => $arParams['LIST_LABEL_PROP_POSITION'],
		'ADD_PICT_PROP' => $arParams['ADD_PICT_PROP'],
		'PRODUCT_DISPLAY_MODE' => $arParams['PRODUCT_DISPLAY_MODE'],
		'PRODUCT_BLOCKS_ORDER' => $arParams['LIST_PRODUCT_BLOCKS_ORDER'],
		'PRODUCT_ROW_VARIANTS' => $alfaTemplateRows ? $alfaTemplateRows : $arParams['LIST_PRODUCT_ROW_VARIANTS'],
		'ENLARGE_PRODUCT' => $arParams['LIST_ENLARGE_PRODUCT'],
		'ENLARGE_PROP' => isset($arParams['LIST_ENLARGE_PROP']) ? $arParams['LIST_ENLARGE_PROP'] : '',
		'SHOW_SLIDER' => $arParams['LIST_SHOW_SLIDER'],
		'SLIDER_INTERVAL' => isset($arParams['LIST_SLIDER_INTERVAL']) ? $arParams['LIST_SLIDER_INTERVAL'] : '',
		'SLIDER_PROGRESS' => isset($arParams['LIST_SLIDER_PROGRESS']) ? $arParams['LIST_SLIDER_PROGRESS'] : '',

		'OFFER_ADD_PICT_PROP' => $arParams['OFFER_ADD_PICT_PROP'],
		'OFFER_TREE_PROPS' => $arParams['OFFER_TREE_PROPS'],
		'PRODUCT_SUBSCRIPTION' => $arParams['PRODUCT_SUBSCRIPTION'],
		'SHOW_DISCOUNT_PERCENT' => $arParams['SHOW_DISCOUNT_PERCENT'],
		'DISCOUNT_PERCENT_POSITION' => $arParams['DISCOUNT_PERCENT_POSITION'],
		'SHOW_OLD_PRICE' => $arParams['SHOW_OLD_PRICE'],
		'SHOW_MAX_QUANTITY' => $arParams['SHOW_MAX_QUANTITY'],
		'MESS_SHOW_MAX_QUANTITY' => (isset($arParams['~MESS_SHOW_MAX_QUANTITY']) ? $arParams['~MESS_SHOW_MAX_QUANTITY'] : ''),
		'RELATIVE_QUANTITY_FACTOR' => (isset($arParams['RELATIVE_QUANTITY_FACTOR']) ? $arParams['RELATIVE_QUANTITY_FACTOR'] : ''),
		'MESS_RELATIVE_QUANTITY_MANY' => (isset($arParams['~MESS_RELATIVE_QUANTITY_MANY']) ? $arParams['~MESS_RELATIVE_QUANTITY_MANY'] : ''),
		'MESS_RELATIVE_QUANTITY_FEW' => (isset($arParams['~MESS_RELATIVE_QUANTITY_FEW']) ? $arParams['~MESS_RELATIVE_QUANTITY_FEW'] : ''),
		'MESS_BTN_BUY' => (isset($arParams['~MESS_BTN_BUY']) ? $arParams['~MESS_BTN_BUY'] : ''),
		'MESS_BTN_ADD_TO_BASKET' => (isset($arParams['~MESS_BTN_ADD_TO_BASKET']) ? $arParams['~MESS_BTN_ADD_TO_BASKET'] : ''),
		'MESS_BTN_SUBSCRIBE' => (isset($arParams['~MESS_BTN_SUBSCRIBE']) ? $arParams['~MESS_BTN_SUBSCRIBE'] : ''),
		'MESS_BTN_DETAIL' => (isset($arParams['~MESS_BTN_DETAIL']) ? $arParams['~MESS_BTN_DETAIL'] : ''),
		'MESS_NOT_AVAILABLE' => (isset($arParams['~MESS_NOT_AVAILABLE']) ? $arParams['~MESS_NOT_AVAILABLE'] : ''),
		'MESS_BTN_COMPARE' => (isset($arParams['~MESS_BTN_COMPARE']) ? $arParams['~MESS_BTN_COMPARE'] : ''),
		'MESS_BTN_ASK' => $arParams['MESS_BTN_ASK'],

		'USE_ENHANCED_ECOMMERCE' => (isset($arParams['USE_ENHANCED_ECOMMERCE']) ? $arParams['USE_ENHANCED_ECOMMERCE'] : ''),
		'DATA_LAYER_NAME' => (isset($arParams['DATA_LAYER_NAME']) ? $arParams['DATA_LAYER_NAME'] : ''),
		'BRAND_PROPERTY' => (isset($arParams['BRAND_PROPERTY']) ? $arParams['BRAND_PROPERTY'] : ''),

		"HIDE_SECTION_NAME" => (isset($arParams["SECTIONS_HIDE_SECTION_NAME"]) ? $arParams["SECTIONS_HIDE_SECTION_NAME"] : "N"),
		"ADD_SECTIONS_CHAIN" => "",
		'ADD_TO_BASKET_ACTION' => $basketAction,
		'ADD_TO_BASKET_ACTION_PRIMARY' => (isset($arParams['DETAIL_ADD_TO_BASKET_ACTION_PRIMARY']) ? $arParams['DETAIL_ADD_TO_BASKET_ACTION_PRIMARY'] : null),
		'SHOW_CLOSE_POPUP' => isset($arParams['COMMON_SHOW_CLOSE_POPUP']) ? $arParams['COMMON_SHOW_CLOSE_POPUP'] : '',
		'COMPARE_PATH' => $arResult['FOLDER'].$arResult['URL_TEMPLATES']['compare'],
		'COMPARE_NAME' => $arParams['COMPARE_NAME'],
		'BACKGROUND_IMAGE' => (isset($arParams['SECTION_BACKGROUND_IMAGE']) ? $arParams['SECTION_BACKGROUND_IMAGE'] : ''),
		'COMPATIBLE_MODE' => (isset($arParams['COMPATIBLE_MODE']) ? $arParams['COMPATIBLE_MODE'] : ''),
		'DISABLE_INIT_JS_IN_COMPONENT' => (isset($arParams['DISABLE_INIT_JS_IN_COMPONENT']) ? $arParams['DISABLE_INIT_JS_IN_COMPONENT'] : ''),

		"TEMPLATE_AJAXID" => $arParams["TEMPLATE_AJAXID"],
		"DISPLAY_PREVIEW_TEXT" => $arParams["LIST_DISPLAY_PREVIEW_TEXT"],
		"PREVIEW_TRUNCATE_LEN" => $arParams["PREVIEW_TRUNCATE_LEN"],
		'COMPOSITE_FRAME' => 'Y',

		'IS_USE_CART' => $arParams['IS_USE_CART'],
		'PRICE_PROP' => $arParams['PRICE_PROP'],
		'DISCOUNT_PROP' => $arParams['DISCOUNT_PROP'],
		'CURRENCY_PROP' => $arParams['CURRENCY_PROP'],
		'PRICE_DECIMALS' => $arParams['PRICE_DECIMALS'],
		//element
		'PATH_TO_CART' => $arParams['BASKET_URL'],
		'MESS_BTN_ASK' => $arParams['MESS_BTN_ASK'],
		'LINK_BTN_ASK' => $arParams['LINK_BTN_ASK'],
		'ELEMENT_ADD_PICT_PROP' => $arParams['ADD_PICT_PROP'],
		'LANDING_ELEMENT_IBLOCK_ID' => $arParams['IBLOCK_ID'],
		'LANDING_ELEMENT_ID' => $arPropLanding['ID'],
		'PROPERTY_CODE_ELEMENT' => $arParams['DETAIL_PROPERTY_CODE'],
		'LANDING_DETAIL_PAGE' => "Y",

	)
);

require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");