<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Вакансии");
?><span style="font-size: 16pt; color: #000000;">Акрустал. История развития&nbsp;&nbsp;</span><br>
 <br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"blog", 
	array(
		"COMPONENT_TEMPLATE" => "blog",
		"IBLOCK_TYPE" => "company",
		"IBLOCK_ID" => "9",
		"NEWS_COUNT" => "20",
		"USE_SEARCH" => "N",
		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_1",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"SIDE_LEFT_BLOCK" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK" => "FROM_MODULE",
		"SIDE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"S_ASK_QUESTION" => "",
		"S_ORDER_SERVISE" => "",
		"FORM_ID_ORDER_SERVISE" => "",
		"T_GALLERY" => "",
		"T_DOCS" => "",
		"T_VIDEO" => "",
		"T_MAX_LINK" => "",
		"T_PREV_LINK" => "",
		"IBLOCK_LINK_NEWS_ID" => "",
		"IBLOCK_LINK_SERVICES_ID" => "",
		"IBLOCK_LINK_TIZERS_ID" => "",
		"IBLOCK_LINK_REVIEWS_ID" => "",
		"IBLOCK_LINK_STAFF_ID" => "",
		"IBLOCK_LINK_VACANCY_ID" => "",
		"IBLOCK_LINK_BLOG_ID" => "",
		"IBLOCK_LINK_PROJECTS_ID" => "",
		"IBLOCK_LINK_BRANDS_ID" => "",
		"IBLOCK_LINK_LANDINGS_ID" => "",
		"BLOCK_SERVICES_NAME" => "",
		"BLOCK_NEWS_NAME" => "",
		"BLOCK_TIZERS_NAME" => "",
		"BLOCK_REVIEWS_NAME" => "",
		"BLOCK_STAFF_NAME" => "",
		"BLOCK_VACANCY_NAME" => "",
		"BLOCK_PROJECTS_NAME" => "",
		"BLOCK_BRANDS_NAME" => "",
		"BLOCK_BLOG_NAME" => "",
		"BLOCK_LANDINGS_NAME" => "",
		"T_GOODS" => "",
		"IBLOCK_LINK_PARTNERS_ID" => "",
		"BLOCK_PARTNERS_NAME" => "",
		"IBLOCK_LINK_SALE_ID" => "",
		"BLOCK_SALE_NAME" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_FILTER_DATE" => "Y",
		"IMAGE_POSITION" => "left",
		"LINE_ELEMENT_COUNT_LIST" => "3",
		"SHOW_ASK_BLOCK" => "N",
		"SHOW_BORDER_ELEMENT" => "N",
		"USE_BG_IMAGE_ALTERNATE" => "N",
		"BG_POSITION" => "top left",
		"TYPE_IMG" => "lg",
		"SIZE_IN_ROW" => "4",
		"TITLE_SHOW_FON" => "Y",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"USE_SUBSCRIBE_IN_TOP" => "N",
		"SHOW_MAX_ELEMENT" => "N",
		"USE_SHARE" => "N",
		"LINKED_ELEMENST_PAGE_COUNT" => "20",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "N",
		"GALLERY_TYPE" => "small",
		"STAFF_TYPE_DETAIL" => "list",
		"DETAIL_LINKED_GOODS_SLIDER" => "Y",
		"DETAIL_BLOCKS_ALL_ORDER" => "tizers,desc,docs,char,goods,services,blog,vacancy,news,sale,form_order,projects,reviews,video,gallery,brands,landings,staff,comments,partners",
		"DETAIL_USE_COMMENTS" => "Y",
		"PRICE_CODE" => array(
		),
		"STORES" => array(
			0 => "",
			1 => "",
		),
		"HIDE_NOT_AVAILABLE" => "N",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"T_ALSO_ITEMS" => "",
		"ALSO_ITEMS_POSITION" => "bottom",
		"LIST_VIEW" => "slider",
		"ALSO_ITEMS_COUNT" => "5",
		"VIEW_TYPE" => "list",
		"SHOW_TABS" => "Y",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SHOW_SECTION_NAME" => "N",
		"SHOW_ASK_QUESTION_BLOCK" => "Y",
		"T_GOODS_SECTION" => "",
		"MAX_GALLERY_GOODS_ITEMS" => "5",
		"COUNT_IN_LINE" => "3",
		"LINKED_PRODUCTS_PROPERTY" => "BRAND",
		"SHOW_LINKED_PRODUCTS" => "N",
		"SHOW_MEASURE" => "N",
		"AJAX_FILTER_CATALOG" => "Y",
		"DEFAULT_LIST_TEMPLATE" => "block",
		"SHOW_UNABLE_SKU_PROPS" => "Y",
		"SHOW_ARTICLE_SKU" => "N",
		"SHOW_MEASURE_WITH_RATIO" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"ALT_TITLE_GET" => "NORMAL",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_DISCOUNT_TIME_EACH_SKU" => "N",
		"SHOW_RATING" => "Y",
		"DISPLAY_COMPARE" => "Y",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => "",
		"LIST_PROPERTY_CATALOG_CODE" => array(
			0 => "",
			1 => "",
		),
		"SORT_BUTTONS" => array(
			0 => "POPULARITY",
			1 => "NAME",
			2 => "PRICE",
		),
		"SHOW_COUNT_ELEMENTS" => "Y",
		"SHOW_GALLERY_GOODS" => "Y",
		"ADD_DETAIL_TO_SLIDER" => "Y",
		"IBLOCK_CATALOG_TYPE" => "-",
		"IBLOCK_CATALOG_ID" => "1",
		"ADD_PICT_PROP" => "",
		"SHOW_GALLERY" => "Y",
		"GALLERY_PRODUCTS_PROPERTY" => "PHOTOS",
		"DEPTH_LEVEL_BRAND" => "2",
		"USE_PRICE_COUNT" => "N",
		"CONVERT_CURRENCY" => "N",
		"SEF_FOLDER" => "/company/history/",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);?><br>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>